services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: mundial
      POSTGRES_PASSWORD: mundial
      POSTGRES_DB: mundial
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
